sudo: required

hosts:
  - feed.bencane.com
  - bencane.com
  
services:
  - docker
  
before_install:
  - docker build -t blog .

install:
  - docker run -d -p 80:80 --name blog blog
  
script:
  - docker ps | grep -q "blog"
  - curl -vk http://bencane.com
  - curl -vk http://feed.bencane.com
