output_dir: /var/tmp/bclog/
static_dir: static
template_dir: ./templates
post_dir: posts
articles:
  config: articles/config
  posts: articles/posts
templates:
  archive: archive.html
  post: blog.html
  index: index.html
  feed: feed.xml
  sitemap: sitemap.xml
  notfound: 404.html
  forbidden: 403.html
site_name: Benjamin Cane
site_description: Linux Systems Administration blog featuring tutorials, tips, hacks and how to articles
site_shortdesc: A Linux Systems Administration Blog
site_thumbnail: http://bencane.com/img/thumbnails/shell.png
site_url: http://bencane.com
site_feed: http://feed.bencane.com
site_keywords: 
  - linux
  - unix
  - sysadmin
  - sysadmin blog
  - devops
  - DevOps How to
  - DevOps Blog
  - Linux Blog
  - linux blog
  - sysadmin best practices
  - systems administration
  - ubuntu
  - redhat
  - linux os
  - Linux Server
  - bash shell
  - linux for dummies
  - learning linux
  - linux operating system
  - Linux tutorials
  - Linux how to
  - Sysadmin tutorials
  - Sysadmin How To
site_author: Benjamin Cane
site_authorlink: https://plus.google.com/+BenjaminCane
index_header: Systems Architect who writes about Linux Systems Administration
