author: bencane
comments: true
date: 2011-09-01 20:01:05+00:00
popularity: None
slug: grep-counting-results
title: 'grep: Counting Results'
post_id: 46
categories:
- Command Line
- Linux
- Linux Commands
tags:
- linux
- tech
- unix
file: 2011-09-01-grep-counting-results.md
