author: bencane
comments: true
date: 2011-08-11 20:33:06+00:00
popularity: None
slug: yes-repeated-text-command-of-the-day
title: 'yes: Repeated Text'
post_id: 30
categories:
- All Articles
- Command Line
- Linux
- Linux Commands
- Unix
- Unix Commands
tags:
- linux
- tech
- unix
file: 2011-08-11-yes-repeated-text-command-of-the-day.md
published: True
